apiVersion: v1
kind: Service
metadata:
  name: shard-worker-service
spec:
  selector:
    name: shard-worker
  ports:
    - name: "communication"
      protocol: TCP
      port: 8981
      targetPort: 8981
    - name: "metrics"
      protocol: TCP
      port: 9091
      targetPort: 9091

